# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    data: ???
    sort_by_length: false
    shuffle: false
    text_data: ''

  common_eval:
    path: ???
    quiet: true

  dataset:
    gen_subset: valid
    batch_size: 1

w2l_decoder: KENLM
lm_model: /work/b07502072/corpus/u-s2s/audio/features/precompute_pca512_cls128_mean_pooled/lm.phones.filtered.06.bin
# lexicon: /work/b07502072/corpus/u-s2s/text/en/en_phon/lexicon.lst
beam: 20
post_process: silence
# not success yet!!!